# Generated by Django 4.2 on 2025-07-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConverterMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("class_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FileFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormatConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_codec", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "audio_video_codec",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("audio_codec", models.CharField(blank=True, max_length=50, null=True)),
                ("engine", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "input_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_from",
                        to="converter.fileformat",
                    ),
                ),
                (
                    "output_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_to",
                        to="converter.fileformat",
                    ),
                ),
            ],
        ),
    ]
